### ISSUE TITLE
No module named 'opensea'

### ISSUE THREAD

**Issue by AnthonyRodriguez726** [zseta/python-opensea#1]
When you copy the code directly from the **Get data about a single asset** section the following error is given: 

```
Traceback (most recent call last):
  File "C:\Users\antho\Desktop\nft-py\index.py", line 1, in <module>
    from opensea import Asset
ModuleNotFoundError: No module named 'opensea'
```

**Comment by zseta** [comment]
Hi @AnthonyRodriguez726,
Did you successfully installed the package before running that snippet? `pip install opensea-api`

**Comment by AnthonyRodriguez726** [comment]
Yep! The package was successfully installed. opensea-api 0.1.2 shows when I `pip list`

[Here's a full screenshot](https://i.imgur.com/mDcwAhu.png)

**Comment by zseta** [comment]
Thanks for the screen! I was actually able to reproduce this error with python3.9. Will try to fix this over the weekend but until then I found that using a [virtualenv](https://virtualenv.pypa.io/en/latest/installation.html#via-pip) fixes the issue:
```bash
virtualenv env && source env/bin/activate
pip install opensea-api
```
Then you should be able to `from opensea import Asset`

**Comment by zseta** [comment]
I reworked the API a little bit (https://github.com/zseta/python-opensea/pull/3) to also support adding API keys as now OpenSea requires them. So will close this issue now, but feel free to open a new one if you have problems in the future!
