### ISSUE TITLE
Include an example that shows how to paginate the /events endpoint

### ISSUE THREAD

**Issue by zseta** [zseta/python-opensea#15]
The one in the readme currently uses the previous pagination method which will stop working soon

**Comment by JohnSweeney85** [comment]
First of all thanks so much for this! 
Secondly...looks like it just stopped working a little bit ago. 

"Start ingesting data between 2022-01-20 00:00:00+00:00 and 2022-02-22 23:09:43.189252+00:00 (time period: 33 days, 23:09:43.189252)
Traceback (most recent call last):
  File "opensea_ingest.py", line 283, in <module>
  `  start_ingest(start_date, end_date, rate_limiting=1)`
  File "opensea_ingest.py", line 257, in start_ingest
   ` next_url = opensea_utils.next_url_fix(first_request["next_url"])`
KeyError:` 'next'`"

**Comment by zseta** [comment]
You're right @CryptusChrist !
Unfortunately, this API change came out of nowhere without warning and completely breaks the new pagination method they introduced...
Seems like now the `next` value is not the full URL but just the cursor hash...

I opened an issue for this (if you feel like you want to give it a go :) https://github.com/zseta/python-opensea/issues/17

**Comment by zseta** [comment]
https://github.com/zseta/python-opensea/pull/17 has been fixed please pull [the repo again](https://github.com/timescale/nft-starter-kit), and run `pip install -r requirements`
(or at least pip install opensea-api -U)
