### ISSUE TITLE
Cursor parameter to events request

### ISSUE THREAD

**Issue by Luca-Blight** [zseta/python-opensea#21]
Is this a parameter that will be added anytime soon?

**Comment by zseta** [comment]
Hi @Royzac !
Is there anything specific you'd want to achieve with that? (there's an [events_backfill()](https://github.com/zseta/python-opensea/blob/05a8d13e961ac74385e6ebfcfb7e0fca72bc8da1/opensea/opensea_api.py#L130) function which might help you?)

**Comment by Luca-Blight** [comment]
@zseta thanks for responding! 
Basically just keep track of events request/response state using the new cursor pagination "upgrade". 
I suppose events_backfill covers that functionality? Btw, excellent job on the development of this library.

**Comment by zseta** [comment]
If you just want to paginate to download multiple pages of event data you can use the `events_backfill()` function, example:
```python
api = OpenseaAPI(apikey="")
event_generator = api.events_backfill(start=datetime(2021, 10, 5, 3, 25, tzinfo=timezone.utc),
                                      until=datetime(2021, 10, 5, 3, 20, tzinfo=timezone.utc),
                                      event_type="successful")
for event in event_generator:
    if event is not None:
        print(event) # or do other things with the event data
```
This will handle the cursor stuff internally.

*(Taken from the [NFT Starter Kit](https://github.com/timescale/nft-starter-kit/blob/6e715184052d374ff32e238ab7dd7b4b3899ab24/opensea_ingest.py#L231).)*

**Comment by Luca-Blight** [comment]
Ah, nice! Thank you!
