### ISSUE TITLE
ConnectionError: The server blocked access.

### ISSUE THREAD

**Issue by Luca-Blight** [zseta/python-opensea#22]
I wonder if this issue is coming from the library or opensea itself?
I scanned through discord and saw a comment of this error a couple months ago with some similarity, pasted below.

"does the api require a key? on the docs it says you dont but when i try to use the opensea python api wrapper i get 
ConnectionError: The server blocked access."

**Comment by zseta** [comment]
This means the API returned `HTTP 403 Forbidden` error. I think OpenSea returns this if no API key is set or if you make too many requests (I'm not sure about the latter)

**Comment by Luca-Blight** [comment]
Indeed, my mistake. Thanks anyways!
