### ISSUE TITLE
Thanks very much

### ISSUE THREAD

**Issue by kaifeitudou** [zseta/python-opensea#33]
when I use the api funciton, I have a error like this:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.opensea.io', port=443): Max retries exceeded with url: /api/v1/collection/cryptopunks (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000010A51A36D90>: Failed to establish a new connection

I had check my web and vpn.

**Comment by zseta** [comment]
Hi @kaifeitudou ,

Seems unrelated to the wrapper library. Is this still an issue? Feel free to re-open if needed.

**Comment by kaifeitudou** [comment]
Thank you very much.
