### ISSUE TITLE
Reguarding rankings opensea

### ISSUE THREAD

**Issue by codingdudepy** [zseta/python-opensea#7]
Wrapper doesnt let me get top rankings on opensea. Any solution?

**Comment by zseta** [comment]
Hi there,

Unfortunately, OpenSea don't have an endpoint that can return collections sorted by volume. (AFAIK)

What might be useful is the CollectionStats endpoint which can return the one day / seven day / thirty day total volume for a given collection. eg using the wrapper library:
```python
from opensea import OpenseaAPI
api = OpenseaAPI(apikey=OPENSEA_APIKEY)
print(api.collection_stats("cryptokitties"))

{
    "stats": {
        "one_day_volume": 56.51351949502994,
        "one_day_change": 30.20564123474754,
        "one_day_sales": 106.0,
        "one_day_average_price": 0.5331464103304712,
        "seven_day_volume": 67.52994154251218,
        "seven_day_change": 1.7123777008310594,
        "seven_day_sales": 530.0,
        "seven_day_average_price": 0.1274149840424758,
        "thirty_day_volume": 178.17623781256253,
        "thirty_day_change": -0.39159353548548675,
        "thirty_day_sales": 2532.0,
        "thirty_day_average_price": 0.0703697621692585,
        "total_volume": 70449.73370135202,
        "total_sales": 776928.0,
        "total_supply": 2010559.0,
        "count": 2010559.0,
        "num_owners": 112695,
        "average_price": 0.09067730047231148,
        "num_reports": 2,
        "market_cap": 256175.3429014561,
        "floor_price": null
    }
}
```

But for this you need to know the collection slugs. (My only idea atm is to scrape them)

**Comment by codingdudepy** [comment]
Hi Thanks For Responding :) So I did try scraping it but it wouldnt get the collection volume. Would you happen to know of any api or any wrapper i can use that can correctly scrape it?

**Comment by zseta** [comment]
Scraping would still be my go-to for this :) (closing this now, feel free to re-open if you have issues/questions)

**Comment by codingdudepy** [comment]
Scraping wont work you get a cloudflare block
