### ISSUE TITLE
Is there any way to get all the collections in Opensea?

### ISSUE THREAD

**Issue by manabu-git** [zseta/python-opensea#8]

**Comment by zseta** [comment]
Hi!

I suppose you could use the collections endpoint and just paginate using offset?
Example:

```python
import time    
from opensea import OpenseaAPI
api = OpenseaAPI(apikey=OPENSEA_APIKEY)

# download collection data in JSON files (300 collections per file)
def get_all_collections():
    offset = 0
    max_items = 300
    i = 0
    while (True):
        result = api.collections(offset=offset, limit=max_items, export_file_name=f"collection_{i}.json")
        if len(result) == 0:
            break
        time.sleep(2)
        offset += max_items
        i += 1
```

**Comment by manabu-git** [comment]
Thanks for showing the sample.

Yes, I have considered the paging.
However, if I set the offset parameter to a value greater than 50000, it returns an error like the following

```
{
  "offset": [
    "ensure this value is less than or equal to 50000"
  ]
}
```
Is it possible to get a collection with more than 50000 items?
Also, I'm currently testing using testnet.

https://testnets-api.opensea.io/api/v1/collections

It's been two weeks since I applied for the API key.
(It's already been two weeks since I applied, but I haven't heard from them!!)

Will the limit be removed when I go to a production environment?

Thanks,

**Comment by cxheng315** [comment]
> Thanks for showing the sample.
> 
> Yes, I have considered the paging. However, if I set the offset parameter to a value greater than 50000, it returns an error like the following
> 
> ```
> {
>   "offset": [
>     "ensure this value is less than or equal to 50000"
>   ]
> }
> ```
> 
> Is it possible to get a collection with more than 50000 items? Also, I'm currently testing using testnet.
> 
> https://testnets-api.opensea.io/api/v1/collections
> 
> It's been two weeks since I applied for the API key. (It's already been two weeks since I applied, but I haven't heard from them!!)
> 
> Will the limit be removed when I go to a production environment?
> 
> Thanks,

Maybe you could try to use cursor instead of offset.
```
While cursor: 
  start paging
```
